Repository larsomic/friend-finder-frontend, pull requests merged in 2023-06, with the labels that each got.

#3 Add persistent storage.
  components/CenteredContainer.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/login.tsx
  pages/logout.tsx
  pages/signup.tsx
  redux/store.tsx
  redux/store_type.tsx
Labels: enhancement

#4 Fix build errors in central state.
  pages/index.tsx
  pages/signup.tsx
  redux/store.tsx
  redux/store_type.tsx
Labels: bug

#8 Update README.md for setup
  README.md
Labels: documentation, frontend

#10 Add authenticated and unauthenticated home page.
  components/AuthenticatedHomePage.tsx
  components/UnauthenticatedHomePage.tsx
  pages/index.tsx
Labels: enhancement

#17 Add name to home andheader
  components/AuthenticatedHomePage.tsx
  components/HeaderBar.tsx
  pages/_app.tsx
  redux/requiredInStoreMiddleware.tsx
  redux/requiredInfoMiddleware.tsx
  redux/store.tsx
  redux/store_type.tsx
  redux/userReducer.tsx
Labels: enhancement

#18 Feature redirecting user login signin logout
  components/HeaderBar.tsx
  pages/login.tsx
  pages/logout.tsx
  pages/signup.tsx
Labels: enhancement, frontend
